### PR TITLE
User can view summary horizontal timeline.

### PR DESCRIPTION
**Pull request by jerrudS**
screen shot 2017-06-15 at 2 25 58 pm
screen shot 2017-06-15 at 2 26 20 pm

### CODE REVIEW

**Comment by jerrudS** [comment]
screen shot 2017-06-16 at 3 11 10 pm

**Comment by ronperris** [comment]
Fix duplicate header content. Your header should only appear once.
image

**Comment by ronperris** [comment]
The colors of the header, primary, background, and buttons don't look right together.

Use a tool like these to find colors that go together.
https://color.adobe.com/create/color-wheel/
http://paletton.com/

**Comment by ronperris** [comment]
All the fields in the form should match in size or be ratio based.

image

**Pull request merged**
